# Generated by Django 3.1.3 on 2020-11-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Point',
            new_name='point',
        ),
    ]
