# Generated by Django 3.1.3 on 2020-11-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
    ]
